#!/bin/sh

# adapted from i3exit

[ "$(cat /proc/1/comm)" = "systemd" ] && logind=systemctl || logind=loginctl

case "$1" in
    lock) # cannot switch to a/o user
        dm-tool lock
        #betterlockscreen -l dimblur
        ;;
    logout)
        i3-msg exit
        ;;
    switch_user)
        dm-tool switch-to-greeter
        ;;
    suspend) # cannot switch to a/o user
        dm-tool lock && $logind suspend
        #betterlockscreen -s dimblur
        # blurlock && $logind suspend
        ;;
    hibernate)
        dm-tool lock && $logind hibernate
        #betterlockscreen -l dimblur && $logind hibernate
        ;;
    reboot)
        $logind reboot
        ;;
    shutdown)
        $logind poweroff
        ;;
    *)
        echo "== ! myi3exit: missing or invalid argument ! =="
        echo "Try again with: lock | logout | switch_user | suspend | hibernate | reboot | shutdown"
        exit 2
esac

exit 0
